#!/usr/bin/env bash
# Generate HTML documentation for all GLOSIS-ext TTL modules using pyLODE.
#
# Why pyLODE instead of WiDoco: WiDoco 1.4.x requires JDK 11+; this machine
# has Java 8 only. pyLODE is Python-based, pip-installable, and produces
# equivalent HTML output (ontdoc profile, embedded favicon, no external deps).
#
# Output: docs/glosis/<module>/index.html
#
# Usage: bash scripts/build-docs.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Locate pylode binary (--user installs go to ~/Library/Python/.../bin on macOS)
PYLODE_BIN="$(command -v pylode || true)"
if [ -z "$PYLODE_BIN" ]; then
  PYLODE_BIN="$HOME/Library/Python/3.9/bin/pylode"
fi
if [ ! -x "$PYLODE_BIN" ]; then
  echo "ERROR: pylode not found. Install with: pip3 install --user 'pylode<3.0'"
  exit 1
fi
echo "Using pylode: $PYLODE_BIN"
"$PYLODE_BIN" --version || true

# TTL files to document (skip shapes.ttl — SHACL shapes don't render well)
TTLS=(
  "data/glosis/geolytics-glosis-ext.ttl:glosis-ext"
  "data/glosis/geolytics-modules.ttl:modules"
  "data/glosis/geolytics-units.ttl:units"
  "data/glosis/geolytics-ep-backbone.ttl:ep-backbone"
  "data/glosis/pvt-procedures.ttl:pvt-procedures"
  "data/glosis/geolytics-petrography-i18n.ttl:petrography-i18n"
)

mkdir -p docs/glosis

for entry in "${TTLS[@]}"; do
  ttl="${entry%%:*}"
  name="${entry##*:}"
  if [ ! -f "$ttl" ]; then
    echo "  SKIP: $ttl not found"
    continue
  fi

  # Pre-validate with rdflib (catches malformed TTL before pyLODE)
  python3 -c "import rdflib; g=rdflib.Graph(); g.parse('$ttl', format='turtle'); print(f'  $ttl: {len(g)} triples')" || {
    echo "  FAIL: $ttl failed rdflib parse"
    exit 1
  }

  outdir="docs/glosis/$name"
  mkdir -p "$outdir"
  echo "  Building $name..."
  "$PYLODE_BIN" -i "$ttl" -o "$outdir/index.html" 2>&1 | tail -2

  # Copy source TTL alongside HTML for content negotiation
  cp "$ttl" "$outdir/ontology.ttl"
done

# Generate landing index
cat > docs/glosis/index.md <<'EOF'
---
layout: default
title: Geolytics × GLOSIS — Reference Documentation
---

# Geolytics × GLOSIS — Reference Documentation

HTML documentation auto-generated by pyLODE for the 6 OWL/SKOS ontology modules in `data/glosis/`.

## Modules

| Module | Description | Triples | HTML |
|---|---|---|---|
| **glosis-ext** | Main integration layer — 4 owl:imports, 99 SKOS mappings, ISO 28258 backbone alias, SOSA Property/Value pattern, PT/ES i18n labels | 593 | [docs](glosis-ext/) · [ttl](glosis-ext/ontology.ttl) |
| **modules** | M7/M8/M9/M10 internal modules (geochemistry, rock physics, geomechanics, PVT/fluids) | 463 | [docs](modules/) · [ttl](modules/ontology.ttl) |
| **units** | E&P unit extensions to QUDT (BBL/D, MCF/D, SCF/STB, RB/STB, °API, psia, cP, mD…) | 123 | [docs](units/) · [ttl](units/ontology.ttl) |
| **ep-backbone** | Full ISO 28258 alias (16 object properties + cardinalities) for Bloco→Locação→Poço→Intervalo→Camada hierarchy | 149 | [docs](ep-backbone/) · [ttl](ep-backbone/ontology.ttl) |
| **pvt-procedures** | 8 PVT analysis procedures (flash/differential liberation, CCE, swelling, separator, viscosity, slim-tube, multi-contact) | 116 | [docs](pvt-procedures/) · [ttl](pvt-procedures/ontology.ttl) |
| **petrography-i18n** | PT/ES SKOS prefLabels for 166 GLOSIS petrography concepts | 336 | [docs](petrography-i18n/) · [ttl](petrography-i18n/ontology.ttl) |

## Source ontologies imported

- **GLOSIS v1.5.1** (CC BY-NC-SA 3.0 IGO) — http://w3id.org/glosis/model/
  - codelists, ISO 28258, procedure, unit modules
- **CGI Simple Lithology** (OGC public spec) — both 201211 + 2016.01 versions
- **INSPIRE Geomorphology + LithologyValue** (EU Public Domain) — http://inspire.ec.europa.eu/codelist/
- **QUDT** (CC BY 4.0) — http://qudt.org/

## Validation

```bash
python3 scripts/validate.py --self-check       # Parse all TTLs + JSONs
python3 scripts/validate.py --crosswalk-audit  # Crosswalk integrity
python3 scripts/validate.py --lang-coverage    # PT/ES coverage
```
EOF

echo ""
echo "Documentation built. Output:"
ls -la docs/glosis/*/index.html 2>&1 | awk '{print "  " $NF, $5"B"}'
echo ""
echo "Local serve: python3 -m http.server 8000 -d docs/"
echo "Visit: http://localhost:8000/glosis/"
